name: snappill
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: ^1.19.1
  easy_debounce: ^2.0.3
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: ^2.0.28
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  http: ^0.13.6
  go_router: 12.1.3
  google_fonts: ^6.2.1
  google_maps: ^8.1.1
  google_maps_flutter: ^2.12.3
  google_maps_flutter_android: ^2.16.1
  google_maps_flutter_ios: ^2.15.4
  google_maps_flutter_platform_interface: ^2.12.1
  google_maps_flutter_web: ^0.5.12+1
  intl: ^0.20.2
  json_path: ^0.7.6
  lottie: ^3.3.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: ^0.10.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  timeago: ^3.7.1
  table_calendar: ^3.0.9
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  xml: ^6.5.0
  cupertino_icons: ^1.0.0

  # 이미지 처리 및 카메라 관련 패키지 추가
  image_picker: ^1.0.4
  image: ^4.1.3
  camera: ^0.10.5+5

  # AI/ML 관련 패키지 (선택사항)
  tflite_flutter: ^0.10.4
  google_mlkit_image_labeling: ^0.9.0
  google_mlkit_text_recognition: ^0.9.0

  # 이미지 유사도 계산을 위한 패키지
  vector_math: ^2.1.4

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/tablet_data_final.json
    # AI 모델 파일들 (필요시 추가)
    #- assets/models/

  fonts:
    - family: CoolIconsLine
      fonts:
        - asset: assets/fonts/cool-icons-line.ttf
    - family: RemixIcons
      fonts:
        - asset: assets/fonts/remix-icons.ttf